apiVersion: apps/v1
kind: Deployment
metadata:
  name: demail-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demail-api
  template:
    metadata:
      labels:
        app: demail-api
    spec:
      containers:
      - name: demail-api-container
        image: dlacreme/demail-api:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1042
        env:
        - name: SMTP_HOSTNAME
          value: smtp.mailtrap.io
        - name: SMTP_PORT
          value: "2525"
        - name: SMTP_USERNAME
          value: "940940247f27d7"
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dlc-secrets
              key: smtp-password
