apiVersion: apps/v1
kind: Deployment
metadata:
  name: did-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did-notifications
  template:
    metadata:
      labels:
        app: did-notifications
    spec:
      containers:
      - name: did-notifications-container
        image: dlacreme/did-notifications:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1042
        env:
        - name: SMTP_HOSTNAME
          value: smtp.mailtrap.io
        - name: SMTP_PORT
          value: "2525"
        - name: SMTP_USERNAME
          value: "940940247f27d7"
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dlc-secrets
              key: smtp-password
